# Generated by Django 4.2.1 on 2023-06-25 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('date_added', models.DateField(auto_now=True)),
            ],
            options={
                'ordering': ['-date_added'],
            },
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.CharField(max_length=5000, null=True)),
                ('total', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=90)),
                ('email', models.CharField(max_length=90)),
                ('address', models.CharField(max_length=200)),
                ('ville', models.CharField(max_length=100)),
                ('pays', models.CharField(max_length=100)),
                ('zipcode', models.CharField(max_length=100)),
                ('date_commande', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date_commande'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(db_index=True, max_length=200)),
                ('title', models.CharField(db_index=True, max_length=200)),
                ('price', models.FloatField()),
                ('description', models.TextField(blank=True, max_length=200)),
                ('image', models.URLField(max_length=500)),
                ('date_added', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(default='', max_length=200, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='lacaseapp.categorie')),
            ],
            options={
                'ordering': ['-date_added'],
            },
        ),
    ]
